# Generated by Django 3.1.6 on 2021-02-27 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_auto_20210224_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ergo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eidos', models.CharField(choices=[('Mpeto', 'Mpeto'), ('Sidero', 'Sidero'), ('Adrani', 'Adrani')], max_length=200, null=True)),
                ('dokimi', models.CharField(choices=[('Dokimi1', 'Dokimi1'), ('Dokimi2', 'Dokimi2'), ('Dokimi3', 'Dokimi3'), ('Dokimi4', 'Dokimi4'), ('Dokimi5', 'Dokimi5'), ('Dokimi6', 'Dokimi6'), ('Dokimi7', 'Dokimi7'), ('Dokimi8', 'Dokimi8')], max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='date_created',
        ),
        migrations.AddField(
            model_name='customer',
            name='afm',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='engineer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
