# Generated by Django 3.1.6 on 2021-02-27 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_application_ergo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ergo',
        ),
        migrations.AddField(
            model_name='application',
            name='ergo',
            field=models.ManyToManyField(to='applications.Ergo'),
        ),
    ]
