# Generated by Django 3.1.6 on 2021-02-27 01:57

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_auto_20210227_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ergo',
            name='dokimi',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Dokimi1', 'Dokimi1'), ('Dokimi2', 'Dokimi2'), ('Dokimi3', 'Dokimi3'), ('Dokimi4', 'Dokimi4'), ('Dokimi5', 'Dokimi5'), ('Dokimi6', 'Dokimi6'), ('Dokimi7', 'Dokimi7'), ('Dokimi8', 'Dokimi8')], max_length=63, null=True),
        ),
    ]
