# Generated by Django 3.1.6 on 2021-03-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_customer_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='ergo',
        ),
        migrations.AddField(
            model_name='application',
            name='ergo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.ergo'),
        ),
    ]
