# Generated by Django 3.1.6 on 2021-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0020_auto_20210302_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dokimi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_dokimis', models.CharField(max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='ergo',
            name='dokimi',
        ),
        migrations.AddField(
            model_name='ergo',
            name='dokimi',
            field=models.ManyToManyField(to='applications.Dokimi'),
        ),
    ]
