# Generated by Django 3.1.6 on 2021-03-11 19:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_auto_20210303_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status_list',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('item_key1', 'Item title 1.1'), ('item_key2', 'Item title 1.2'), ('item_key3', 'Item title 1.3'), ('item_key4', 'Item title 1.4'), ('item_key5', 'Item title 1.5')], max_length=49, null=True),
        ),
    ]
