# Generated by Django 3.1.6 on 2021-03-12 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_application_status_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='status_list',
        ),
        migrations.AddField(
            model_name='application',
            name='trials',
            field=models.ManyToManyField(to='applications.Trial'),
        ),
    ]
