# Generated by Django 3.1.6 on 2021-03-14 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_auto_20210312_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='trial',
            name='yliko',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='applications.ergo'),
        ),
    ]
